# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Embarque' do

pod 'Parse', '~> 1.7'
pod 'SDWebImage', '~> 3.7'
pod 'Block-KVO'
pod 'Appirater'
pod 'MXGoogleAnalytics'
pod 'Lockbox'

end

target 'EmbarqueTests' do

end

